def archive_configs(environment) {
    sh "rsync backup/* ignw@10.10.0.254:/home/ignw/my_network_as_code/archive/$environment/$BUILD_ID"
}

node {
    stage ('Checkout Repository') {
    deleteDir()
    checkout scm
    }

    stage ('Setup Environment') {
        sh 'python3 -m venv jenkins_build'
        sh 'jenkins_build/bin/python -m pip install -r requirements.txt'
        sh 'git clone https://github.com/carlniger/napalm-ansible'
        sh 'cp -r napalm-ansible/napalm_ansible/ jenkins_build/lib/python3.6/site-packages/'
        sh 'jenkins_build/bin/python napalm-ansible/setup.py install'
        sh '''sed -i -e 's/\\/usr\\/local/jenkins_build/g' ansible.cfg'''
        sh '''sed -i -e 's/dist-/site-/g' ansible.cfg'''
        sh '''sed -i -e 's/\\/usr\\/bin/jenkins_build\\/bin/g' ansible.cfg'''
        sh '''sed -i -e 's/\\/usr\\/bin\\/python3/\\/var\\/lib\\/jenkins\\/jobs\\/my_network_as_code\\/workspace\\/jenkins_build\\/bin\\/python/g' asa_scp.py'''
    }

    stage ('Validate Generate Configurations Playbook') {
        sh 'ansible-playbook generate_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python" --syntax-check'
    }

    stage ('Render Configurations') {
        sh 'ansible-playbook generate_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python"'
    }

    stage ('Unit Testing') {
        sh 'ansible-playbook deploy_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python" --syntax-check'
        sh 'ansible-playbook validate_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python" --syntax-check'
        sh 'ansible-playbook backup_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python" --syntax-check'
        sh 'ansible-playbook replace_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python" --syntax-check'
    }

    stage ('Backup Dev Configurations') {
        sh 'ansible-playbook backup_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python"'
        archive_configs('dev')
    }

    stage ('Deploy Configurations to Dev') {
        sh 'ansible-playbook deploy_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python"'
    }

    stage ('Functional/Integration Testing Dev') {
        def r = sh(script: 'ansible-playbook validate_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python"', returnStatus: true)
        if(r > 0) {
            sh 'ansible-playbook replace_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python"'
           currentBuild.result = 'ABORTED'
           error('Integration testing FAILED')
       }
    }

    stage ('Cleanup after Dev Tasks') {
       sh 'rm backup/*'
    }
 
    stage ('Backup Prod Configurations') {
        sh 'ansible-playbook backup_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python" -i inventory_production'
        archive_configs('prod')
    }

    stage ('Deploy Configurations to Prod') {
        sh 'ansible-playbook deploy_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python" -i inventory_production'
    }

    stage ('Functional/Integration Testing Prod') {
        def r = sh(script: 'ansible-playbook validate_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python" -i inventory_production', returnStatus: true)
        if(r > 0) {
            sh 'ansible-playbook replace_configurations.yaml -e "ansible_python_interpreter=jenkins_build/bin/python" -i inventory_production'
           currentBuild.result = 'ABORTED'
           error('Integration testing FAILED')
       }
    }

}

